theme: jekyll-theme-cayman
title: Machine Reading Comprehension (MRC)
description: This is a Machine Reading Comprehension (MRC) experiment project, which includes implementations and experiments for various MRC tasks (e.g. SQuAD, CoQA, QuAC, etc.)